version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "EnvironmentVariablesExample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s4bev8b7k3xe"
s3_prefix = "EnvironmentVariablesExample"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
